### ISSUE TITLE
Electron doesn't launch with npm run dev

### ISSUE THREAD

**Issue by lyptt** [SimulatedGREG/electron-vue#114]
##### Describe the issue / bug.
Electron doesn't launch with npm run dev

##### How can I reproduce this problem?
Create brand new project following the exact instructions on this repository
Run npm install
Run npm run dev

Expected:
Electron to open

Actual:
Electron doesn't open, ever.

##### If visual, provide a screenshot.
N/A

##### Tell me about your development environment.
  * Node version: 6.8.1
  * NPM version: 3.10.8
  * Operating System: macOS 10.12

Updating tasks/runner.js to search for 'Compiled successfully' instead of 'VALID' got electron launching.

**Comment by kpaekn** [comment]
+1 The same issue for me

### Tell me about your development environment.
- Node version: 7.2.0
- NPM version: 3.10.9
- Operating System: Windows 10.0.14393

The suggested change (~ search for 'Compiled successfully' ~) worked.

**Comment by SimulatedGREG** [comment]
Currently out of the house but I'm assuming webpack made an unexpected
change. Will investigate and resolve soon. Thanks for the catch guys!

**Comment by SimulatedGREG** [comment]
Wepback indeed pushed out a change. Pushing out fix shortly.

**Comment by rdpascua** [comment]
hi greg I'm still using the old `electron-vue` i've also encountered the same issue. What quickfix we can do to make the app work

**Comment by SimulatedGREG** [comment]
To @rdpascua and anybody that runs into this problem.

Simply update the regex from `/VALID/g` to ` /Compiled successfully/g` found in `tasks/runner.js` line 36.

**Fixed in commit** https://github.com/SimulatedGREG/electron-vue/commit/a7e3131668f8fb8c2454b673a189185e41fb29c7

**Comment by davidbernstein** [comment]
Thanks, I had this problem and it’s fixed now.

**Comment by patleeman** [comment]
This fixed the issue on OSx but on windows it wouldn't start electron. I tried re-installing dependencies with npm install --reinstall but that didn't fix it.

I added a really ugly or condition and it seems to be working now:

```
if ((/Compiled successfully/g.test(data.toString().trim().replace(/\n/g, '\n' + repeat(' ', command.length + 2))) && !isElectronOpen) || (/VALID/g.test(data.toString().trim().replace(/\n/g, '\n' + repeat(' ', command.length + 2))) && !isElectronOpen)) {
      console.log(`${BLUE}Starting electron...\n${END}`)
      run('cross-env NODE_ENV=development electron app/src/main/index.dev.js', BLUE, 'electron')
      isElectronOpen = true
    }
```

It might just be me, but just in case anyone else ran into this issue.

**Comment by SimulatedGREG** [comment]
@patleeman 

Can you confirm you `webpack` & `webpack-dev-server` versions by running `npm ls webpack webpack-dev-server`.

**Comment by patleeman** [comment]
@SimulatedGREG 

Hey Greg,  here's the output

```
+-- webpack@2.2.0
`-- webpack-dev-server@2.2.0
```

**Comment by SimulatedGREG** [comment]
@patleeman 

Sorry for the late reply. Could you try manually updating `webpack` and `webpack-dev-server` to their latest versions.

**Comment by patleeman** [comment]
Hey @SimulatedGREG, looks like the update to 2.2.1 worked.  It's working on Windows 10 now.

Thanks!
