### ISSUE TITLE
Chrome Dev-Tools error?

### ISSUE THREAD

**Issue by emjimadhu** [SimulatedGREG/electron-vue#389]
##### Describe the issue / bug.
\# the foloowing error was generated for `chrome dev-tools`

`Debugger listening on ws://127.0.0.1:5858/1b82eabb-e1e6-4815-ba86-ac09e1c88c9e
  For help see https://nodejs.org/en/docs/inspector`

`[21394:0911/142528.962736:ERROR:CONSOLE(7323)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtool
s/bundled/inspector.js (7323)`

`[21394:0911/142529.961727:ERROR:CONSOLE(7323)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtool
s/bundled/inspector.js (7323)`

`[21394:0911/142530.391103:ERROR:CONSOLE(7323)] "Extension server error: Operation failed: http://localhost:9080/ has no execution c
ontext", source: chrome-devtools://devtools/bundled/inspector.js (7323)`

##### Tell me about your development environment.
  * Node version: 8.4.0
  * NPM version: 5.4.1
  * Operating System: Ubuntu 16.04 LTS

**Comment by spiritfire** [comment]
i got the same ERROR with ELECTRON 1.7.X.
but if i use ELECTRON 1.6.5, the Error gone. 
i don't know why.

**Comment by SimulatedGREG** [comment]
This is not a specific issue to electron-vue. If you need further help please reach out to `electron` or their respected communities.

**Comment by olafahn** [comment]
I had simliar issue

![screenshot from 2017-10-10 18-01-35](https://user-images.githubusercontent.com/7765194/31378074-15090f6a-ade5-11e7-8cc2-a810cc1310d7.png)

with yarn (1.2.0)

---

surprisingly, with npm install && npm run dev, everything works fine (^^??)
So if there is someone who suffers problem like me, **try to use npm instead of yarn**.

**Comment by AlexVFornazieri** [comment]
@olafahn and @emjimadhu 

I get same issue here using npm, does not update and this error message appears in the terminal.

Does anyone know why? 

**The terminal error**

┏ Electron -------------------
  [14924:0115/000719.276975:ERROR:CONSOLE(7323)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/inspector.js (7323)
┗ ----------------------------

**Tell me about your development environment.**
- Node version: 8.9.4
- NPM version: 5.6.0
- Electron:  1.8.1,
- OS: Ubuntu 16.04 LTS

**Comment by mattRedBox** [comment]
@oalafahn and @emjimadhu
Don't know if it helps, but for me I had occasionally got this issue when experimenting a lot with different libraries. Never investigated why, but got around it by removing electron from node_modules and then running `yarn`.
For me, this resolved the issue.

**Comment by MeirionHughes** [comment]
anyone brought this up on yarn yet?

**Comment by luizguilhermefr** [comment]
+1

**Comment by MaximeAubanel** [comment]
+1

**Comment by code-hearted** [comment]
I am getting the same error has no execution c ontext", source: chrome-devtools://devtools/bundled/inspector.js (7323)

**Comment by cwill** [comment]
+1

**Comment by HernanCabrera** [comment]
Estoy con el mismo problema

**Comment by Solhan0** [comment]
Same here `[13852:0813/170424.451:ERROR:CONSOLE(7323)] "Extension server error: Operation failed: : has no execution context", source: chrome-devtools://devtools/bundled/inspector.js (7323)`

**Comment by dractw** [comment]
Same issue, fix required

**Comment by takidelfin** [comment]
Same issue :/
```bash
[3480:0819/161535.280:ERROR:CONSOLE(7323)] "Extension server error: Operation failed: : has no execution context", source: chrome-devtools://devtools/bundled/inspector.js (7323)
```
- Node v.9.5.0
- NPM v.6.2.0
- Electron ^1.7.5
- VueElectron ^1.0.6
- Vue ^2.3.3

**Comment by sergiocastrovale** [comment]
Any news about this issue yet?

**Comment by XanderLuciano** [comment]
Is this an issue with the template, or with individual projects and / or machines? If someone has a reproducible error please create a separate issue with the code or steps to reproduce. So far this doesn't seem directly related to the template. At this point it would be better to open a new issue with with a reproducible error and then referencing this issue. 

This issue was originally created a year ago, and we've since updated a large portion of this template (including moving to webpack 4), so any new errors with the template should be a separate issue.

Thanks

**Comment by leogoncalves** [comment]
For now, I just forced the firebase **downgrade** to version **4.6.2**. It seems to work for now. It may be a big technical debt, but it works.

**Comment by robbylucia** [comment]
Same issue, but this issue has been closed for over a year,  so...

**Comment by MaverickMartyn** [comment]
I think I found a workaround. It seems to be a temporary issue.
Closing and reopening the dev tool s with `CTRL+SHIFT+I` seemed to fix it for me.

**Comment by craigvantonder** [comment]
I had the same issue, my workaround is:

In main/index.dev.js:

    // Depends on
    const { app } = require('electron')
    // Bringing this up to date as per the usage guidelines: https://github.com/MarshallOfSound/electron-devtools-installer#usage
    const { default: installExtension, VUEJS_DEVTOOLS } = require('electron-devtools-installer')

    // Install `electron-debug` with `devtron`
    // NB: Don't open dev tools with this, it is causing the error
    require('electron-debug')()

    // Install `vue-devtools`
    app.on('ready', () => {
      installExtension(VUEJS_DEVTOOLS)
      .then((name) => console.log(`Added Extension:  ${name}`))
      .catch((err) => console.log('An error occurred: ', err))
    })

In main/index.js:

    function createWindow () {
      ...
      // Open dev tools initially when in development mode
      if (process.env.NODE_ENV === 'development') windowOptions.webPreferences = { devTools: true }
      mainWindow = new BrowserWindow(windowOptions)
      ...
    }

**Comment by Gospodin** [comment]
Hello, I had the same error also, and resolved it by next way. I have updated electron manually to last version and all related modules and have downgraded node to version 10 from 11.

**Comment by daniloprates** [comment]
Any news on this?

**Comment by lowrider-fn** [comment]
I had a similar problem. Here, the https://github.com/SimulatedGREG/electron-vue/issues/389#issuecomment-446165474 solution partially helped me. In index.dev.js, I changed the showDevTools property to false. As written above, this error will probably occur when the DOM is not loaded and devtools are called. I use vuetify and I have a DOM boot error that also killed the system. So the DOM boot handler here might be superfluous.

**Comment by cwill** [comment]
Leaving notes for the future, since I've fixed it

The root cause for me turned out to be a long-running / non-terminating function call inside of a `mounted()` hook. My guess is that if the mount hook takes long enough, the rendering can't finish and the dev tools can't start properly. Changing the problem call to run asynchronously fixed the issue for me.

To figure out where the problem was coming from, starting at the root component of the vue app and commenting out sets of components helped narrow it down to the one causing the issue.

**Comment by daniloprates** [comment]
This is how I fixed it:

```diff
+   window.webContents.on('did-frame-finish-load', () => {
    if (isDev) {
      window.webContents.openDevTools();
      window.webContents.on('devtools-opened', () => {
        window.focus();
      });
    }
+  });
```

**Comment by daniloprates** [comment]
However I'm still having this issue, which I just can't fix:

`[25476:0207/111215.664788:ERROR:CONSOLE(5509)] "SyntaxError: Unexpected token 髍 in JSON at position 1738319", source: chrome-devtools://devtools/bundled/shell.js (5509)`

**Comment by gurpal2000** [comment]
> This is how I fixed it:
> 
> ```diff
> +   window.webContents.on('did-frame-finish-load', () => {
>     if (isDev) {
>       window.webContents.openDevTools();
>       window.webContents.on('devtools-opened', () => {
>         window.focus();
>       });
>     }
> +  });
> ```

Sorry which file and lines?

**Comment by daniloprates** [comment]
> ```diff
> window.webContents.openDevTools();
> ```

@gurpal2000 where-ever you call `window.webContents.openDevTools();`.

You have to wrap it with the `did-frame-finish-load` event, so you only open the dev tools when the frame window was loaded.

**Comment by stefnotch** [comment]
**In main/index.dev.js:**
```diff
- require('electron-debug')({ showDevTools: true });
+ // NB: Don't open dev tools with this, it is causing the error
+ require('electron-debug')();
```

**In main/index.js in the createWindow() function:**
```diff
mainWindow.loadURL(winURL);

+  // Open dev tools initially when in development mode
+  if (process.env.NODE_ENV === "development") {
+    mainWindow.webContents.on("did-frame-finish-load", () => {
+      mainWindow.webContents.once("devtools-opened", () => {
+        mainWindow.focus();
+      });
+      mainWindow.webContents.openDevTools();
+    });
+  }
```

**Comment by stefnotch** [comment]
@SimulatedGREG [That](https://github.com/SimulatedGREG/electron-vue/issues/389#issuecomment-475348490) seems fix the issue. Should I open a pull request?

**Comment by jaysaurus** [comment]
I've tried the method above and I'm still stuck with a frozen blank screen.

**Comment by daniloprates** [comment]
> I've tried the method above and I'm still stuck with a frozen blank screen.

@jaysaurus it's probably a different problem. The one mentioned here doesn't prevent the renderer process to run.

**Comment by jaysaurus** [comment]
My suspicion, after a lot of experimentation, is that this is a thread issue (in my case).   It seemed to coincide with a lot of work ongoing between the renderer thread and the main thread.  Ultimately, I had to switch to a different implementation because (though I got it working on-and-off by killing the cache, removing the dist folder and completely reinstalling the NPM components) things proved to be wildly unstable.  I'm now using Quasar's implementation of vue-electron and it works really well.  It's a pity because - on the whole - I prefer not to use a framework on top of a framework; and the Quasar implementation doesn't support vuex-electron right now. ho hum!

**Comment by craigvantonder** [comment]
@jaysaurus I think the screen goes white when there's a compilation issue, likely a mis-configuration in your main or renderer scripts, could try to add some debugging code or try / catch blocks to see where / when it is bugging out.

I think this boilerplate should be used more as a chance to learn about the implementing vue with webpack and electron, it still works though, try my example adjustments above.

**Comment by jaysaurus** [comment]
Yeah, I tried a bunch of different things to no avail.  My suspicion is we're takling a lower level issue related to a file IO issue being cached.  My program makes a lot of reads of a very legacy hex file (i'm effectively reading a file as if it were being read by an old piece of hardware so there's pretty much no way around throttling the file IO).  My educated guess would be that - given enough file IO and an interrupt from the renderer occuring when the main thread is occupied - you end up with some kind of soft lock where V8 doesn't know which task to prioritise.  Ergo, IRQ stuff.  This lock then gets cached all-over-the shop and the renderer falls over.  thereafter, trying to run the file racks up 1.5gb of processing (probably Electron's equivalent of Java's xmx)  and i get nothing more than a blank window.

**Comment by zjhmale** [comment]
@stefnotch @SimulatedGREG what is the reason that no PR on the ground already based on @stefnotch's workaround, I think this issue bothered most of the newbies who want to use this awesome project at the very first day 😅

**Comment by Constaline** [comment]
Upgrading `electron-debug@3.0.1` can fix this problem, but `electron-debug@3.0.1` requires Electron 5 or later.

**Comment by crstnmac** [comment]
Any update on this issue?

**Comment by crstnmac** [comment]
```
  ipcMain.on("open-devtools", () => {
    browserWindow?.webContents.openDevTools();
  });
```
