### ISSUE TITLE
Webpack ReferenceError: process is not defined

### ISSUE THREAD

**Issue by LionelGarcia** [SimulatedGREG/electron-vue#871]
##### Issue
Fresh electron-vue project gives webpack error:
`ReferenceError: process is not defined`

<img width="658" alt="Capture d’écran 2019-05-05 à 15 58 26" src="https://user-images.githubusercontent.com/20612771/57195098-e7e22300-6f4e-11e9-84f9-5d9ed71c7d8d.png">
Look like issue #516 solved by #726 for build:web

##### Reproduction
```shell
vue init simulatedgreg/electron-vue test_vue_error
cd test_vue_error
npm install
npm run dev
```

##### Screenshot of rendering error
<img width="737" alt="Capture d’écran 2019-05-05 à 15 45 05" src="https://user-images.githubusercontent.com/20612771/57194943-35f62700-6f4d-11e9-872c-585cf6ac5109.png">

##### Development environment
  * Node version: v12.1.0
  * NPM version: 6.9.0
  * vue-cli version: 2.9.6
  * Vue version: 2.6.10
  * Webpack version: 4.30.0
  * Operating System: OSX 10.14.4

**Comment by LionelGarcia** [comment]
Solved by removing:
```html
<% if (!process.browser) { %>
    <script>
        if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
    </script>
<% } %>
```

from `src/index.ejs:16`

Might not be the right solution but works as a temporary fix for me. Not sure issue should be closed though!

**Comment by jeremyfromearth** [comment]
I also ran into this issue. Is it possible that your Node version changed? I find that I can replicate this problem consistently by upgrading/downgrading Node, using NVM to switch between various versions. The fix, for me, was to `rm -rf node_modules; npm i; npm run dev`.

**Comment by wubzz** [comment]
Experiencing the same issue on Node 12.2.0. Not sure what causes it, and not entirely convinced the issue is in this repo. Probably a dependency. Removing parts from the template will work for `npm run dev`, but not so much for `npm run build` or `npm run pack`.

My temporary solution was to do modify `HtmlWebpackPlugin` in `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js`:

```javascript
new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      },
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      },
      nodeModules: false
    }),
```

**Comment by jeremyfromearth** [comment]
I refactored my project to use this: https://github.com/nklayman/vue-cli-plugin-electron-builder. Works w/ Node 12, is generally simpler and more well documented.

**Comment by JBtje** [comment]
This problem might have something to do with upgrading to >v5.0.0 of Electron...
in v4.2.1 I have no problems.
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-50

The same problem, but with "require" seems to be solved when overriding the default value for 
`nodeIntegration` (see link above)

but for me, it already was false... and that works in v4.2.1

**Comment by JBtje** [comment]
The same error appeared after updating nodejs to 12.2.0 (in 11 it was all working). The solution of wubzz solves it.

**Comment by AIMentalModel** [comment]
> Experiencing the same issue on Node 12.2.0. Not sure what causes it, and not entirely convinced the issue is in this repo. Probably a dependency. Removing parts from the template will work for `npm run dev`, but not so much for `npm run build` or `npm run pack`.
> 
> My temporary solution was to do modify `HtmlWebpackPlugin` in `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js`:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```

I'm a new boy for javascript, how to do that, detail please

**Comment by kmaher9** [comment]
@AIMentalModel have you first tried the solution from @LionelGarcia - about removing the section from the index.ejs file? I only mention because it has worked well for me.

link to the comment -> https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-489556092

**Comment by BorysTyminski** [comment]
I also run into this issue after upgraded version of node to latest. I need v12 to use web workers. I don't think removing following:

    
    <% if (!process.browser) { %>
      <script>
        if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
      </script>
    <% } %>

is a real solution. I'm not sure how it will behavior when I'll switch from development to production. Any thoughts about that?

**Comment by AIMentalModel** [comment]
@kmaher9 
i think i test it first by that solution, but i have something error for my project. 
my work need a component for vue,  but i take the error ,so i use that component for electron-react.
sorry about that.

**Comment by kmaher9** [comment]
> @kmaher9
> i think i test it first by that solution, but i have something error for my project.
> my work need a component for vue, but i take the error ,so i use that component for electron-react.
> sorry about that.

Cool well I'm glad you found a solution, consider closing this ticket off if your issue is resolved :)

**Comment by nattvara** [comment]
Seems to work for me using an older node version, node `v11.15.0` works, with node `v12.x` i get the `ReferenceError: process is not defined` error

**Comment by xtx1130** [comment]
in `electron v5.x`. You should add`nodeIntegration` in main process
```js
mainWindow = new BrowserWindow({
    height: 563,
    useContentSize: true,
    width: 1000,
    title: 'TBFE',
    webPreferences: {
      nodeIntegration: true // add this
    }
  })
```
And it will resolve this problem.

**Comment by hiepvq** [comment]
add this code solved the problem for me
```javascript
templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      }
```

**Comment by tvortsa** [comment]
> add this code solved the problem for me
> 
> ```js
> templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       }
> ```

where add this your code ?

**Comment by hiepvq** [comment]
> > add this code solved the problem for me
> > ```js
> > templateParameters(compilation, assets, options) {
> >         return {
> >           compilation: compilation,
> >           webpack: compilation.getStats().toJson(),
> >           webpackConfig: compilation.options,
> >           htmlWebpackPlugin: {
> >             files: assets,
> >             options: options
> >           },
> >           process,
> >         };
> >       }
> > ```
> 
> where add this your code ?

..\.electron-vue\webpack.renderer.config.js
..\.electron-vue\webpack.web.config.js

new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      },
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      },
      nodeModules: false
    }),

**Comment by hulkyhawk** [comment]
i tried and only solution from @wubzz  works

**Comment by burzum** [comment]
I have the same issue... :(
```sh
λ npm -v
6.10.3
λ yarn -v
1.15.2
λ node -v
v12.8.0
```

**Comment by ErcilioMarques** [comment]
i had same issue,  I was using node 12 so i changed to node 10 using nvm

**Comment by pengxinglei** [comment]
i adopt a suggestion @wubzz , but there are new problems now.

**Comment by yikuo123** [comment]
I edit webpack.renderer.config.js as below:

```javascript
new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      },
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== 'production',
      nodeModules: process.env.NODE_ENV !== 'production'
        ? path.resolve(__dirname, '../node_modules')
        : false
    }),
```

and then change index.ejs like this:

```ejs
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <% if (htmlWebpackPlugin.options.nodeModules) { %>
        <!-- Add `node_modules/` to global paths so `require` works properly in development -->
        <script>
          require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
        </script>
    <% } %>
</head>
<body>

<div id="app">
</div>

<!-- Set `__static` path to static files in production -->
<% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
    <script>
      window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
    </script>
<% } %>

<!-- webpack builds are automatically injected -->
</body>
</html>

```

it just drops "process" and works perfectly for me.

I hope this can help you.

**Comment by snowdream** [comment]
I have the same issue

npm -v
6.10.2

yarn -v
1.7.0

node -v
v12.8.1

**Comment by jdfwarrior** [comment]
For this to have a PR that was merged to master and supposedly fixed the issue, I'm still getting the same error as well.

**Comment by baruchiro** [comment]
I have the same issue.
But earlier today, it didn't happen in Windows.

**Comment by aliraza114** [comment]
> in `electron v5.x`. You should add`nodeIntegration` in main process
> 
> ```js
> mainWindow = new BrowserWindow({
>     height: 563,
>     useContentSize: true,
>     width: 1000,
>     title: 'TBFE',
>     webPreferences: {
>       nodeIntegration: true // add this
>     }
>   })
> ```
> 
> And it will resolve this problem.

solved

**Comment by mbach04** [comment]
> I edit webpack.renderer.config.js as below:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: process.env.NODE_ENV !== 'production'
>         ? path.resolve(__dirname, '../node_modules')
>         : false
>     }),
> ```
> 
> and then change index.ejs like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="zh">
> <head>
>     <meta charset="utf-8">
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>         
>         <script>
>           require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>         </script>
>     <% } %>
> </head>
> <body>
> 
> <div id="app">
> </div>
> 
> 
> <% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
>     <script>
>       window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> 
> 
> </body>
> </html>
> ```
> 
> it just drops "process" and works perfectly for me.
> 
> I hope this can help you.

This worked for me. Thanks
--Node version v12.10.0

**Comment by Meilyn** [comment]
> Seems to work for me using an older node version, node `v11.15.0` works, with node `v12.x` i get the `ReferenceError: process is not defined` error

True! I spend 2 days deleting code, add code and in the end it was my node version! So, WITH node V12 really don't work! Use an older and there you have it!

**Comment by encryptedtouhid** [comment]
> I edit webpack.renderer.config.js as below:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: process.env.NODE_ENV !== 'production'
>         ? path.resolve(__dirname, '../node_modules')
>         : false
>     }),
> ```
> 
> and then change index.ejs like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="zh">
> <head>
>     <meta charset="utf-8">
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>         
>         <script>
>           require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>         </script>
>     <% } %>
> </head>
> <body>
> 
> <div id="app">
> </div>
> 
> 
> <% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
>     <script>
>       window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> 
> 
> </body>
> </html>
> ```
> 
> it just drops "process" and works perfectly for me.
> 
> I hope this can help you.

this works fine. thanks buddy

**Comment by reezooh** [comment]
> I edit webpack.renderer.config.js as below:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: process.env.NODE_ENV !== 'production'
>         ? path.resolve(__dirname, '../node_modules')
>         : false
>     }),
> ```
> 
> and then change index.ejs like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="zh">
> <head>
>     <meta charset="utf-8">
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>         
>         <script>
>           require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>         </script>
>     <% } %>
> </head>
> <body>
> 
> <div id="app">
> </div>
> 
> 
> <% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
>     <script>
>       window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> 
> 
> </body>
> </html>
> ```
> 
> it just drops "process" and works perfectly for me.
> 
> I hope this can help you.

This works.

Many thanks!

**Comment by lemtasev** [comment]
All solution of this issues works for me. 
But I still not really understand why.

My node version is v12.13.1.

I am new guy for js and node

**Comment by ChrisKader** [comment]
https://github.com/nodejs/node/pull/26882

Pretty much in node v12+ you need to explicitly import the process module.

Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>vest</title>
    <% if (htmlWebpackPlugin.options.nodeModules) { %>
      <!-- Add `node_modules/` to global paths so `require` works properly in development -->
      <script>
        require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
      </script>
    <% } %>
  </head>
  <body>
    <div id="app"></div>
    <!-- Set `__static` path to static files in production -->
    <%  if (!require('process').browser) { %>
      <script>
        if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
      </script>
    <% } %>

    <!-- webpack builds are automatically injected -->
  </body>
</html>
```

**Comment by feiquan666** [comment]
@ChrisKader 你的时非常正确的解决方案，希望大家采用他的解决方案。——node12.8的工作者的一句忠告。——i am from china

**Comment by cdwmhcc** [comment]
> [nodejs/node#26882](https://github.com/nodejs/node/pull/26882)
> 
> Pretty much in node v12+ you need to explicitly import the process module.
> 
> Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <title>vest</title>
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>       
>       <script>
>         require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>       </script>
>     <% } %>
>   </head>
>   <body>
>     <div id="app"></div>
>     
>     <%  if (!require('process').browser) { %>
>       <script>
>         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>       </script>
>     <% } %>
> 
>     
>   </body>
> </html>
> ```

Thank you!

**Comment by mmm8955405** [comment]
```
Method 1:
require('process').browser

Method 2:
templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
```
Either way, after being packaged as a web or app, the menu will not display correctly. But it can be displayed in the dev environment.

What the hell?
![test](https://user-images.githubusercontent.com/5687907/70859777-b05f3e80-1f53-11ea-8772-b4e9cfe22066.png)

**Comment by hizhaoyun** [comment]
> [nodejs/node#26882](https://github.com/nodejs/node/pull/26882)
> 
> Pretty much in node v12+ you need to explicitly import the process module.
> 
> Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <title>vest</title>
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>       
>       <script>
>         require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>       </script>
>     <% } %>
>   </head>
>   <body>
>     <div id="app"></div>
>     
>     <%  if (!require('process').browser) { %>
>       <script>
>         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>       </script>
>     <% } %>
> 
>     
>   </body>
> </html>
> ```

it work well, thanks~

**Comment by hyjiacan** [comment]
> I refactored my project to use this: https://github.com/nklayman/vue-cli-plugin-electron-builder. Works w/ Node 12, is generally simpler and more well documented.

Cannot agree more, this works better, and the  `vue-cli3/4` supported.

**Comment by RyanChent** [comment]
> I edit webpack.renderer.config.js as below:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: process.env.NODE_ENV !== 'production'
>         ? path.resolve(__dirname, '../node_modules')
>         : false
>     }),
> ```
> 
> and then change index.ejs like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="zh">
> <head>
>     <meta charset="utf-8">
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>         
>         <script>
>           require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>         </script>
>     <% } %>
> </head>
> <body>
> 
> <div id="app">
> </div>
> 
> 
> <% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
>     <script>
>       window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> 
> 
> </body>
> </html>
> ```
> 
> it just drops "process" and works perfectly for me.
> 
> I hope this can help you.

thank you, my node version is 12.14.1, this works for me.

**Comment by Taalaybek** [comment]
did anybody  explain what is error mean?

**Comment by KaKi87** [comment]
Is the [temporary fix](https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-490370237) backwards compatible with Node v10.x ? Thanks

**Comment by blackw212** [comment]
This problem is really annoying, do we get an official fix in order to use latest version of Node? Would be nice, since this post is almost one year old, otherwise fuck this package and i'm going with other solutions...

**Comment by KaKi87** [comment]
@blackw212 Electron + Parcel works 99% fine 😉

**Comment by panovr** [comment]
I can confirm @ChrisKader solution fix this error.

**Comment by bhaskar-nair2** [comment]
When you need to re-configure half of the project to just run hello world, you know that you should not even go near that plugin.. I recommend using https://github.com/nklayman/vue-cli-plugin-electron-builder just imported to my premade project and BAM everything works!

**Comment by PatricNox** [comment]
Any node version below 12 seems to work. 
I had node 13, and got this error. Used NVM to attempt with 10.19, and it works just fine.

So, version compability issue?

**Comment by PatricNox** [comment]
Seems to also be general for Electron and not specifically this project.

**Comment by jdfwarrior** [comment]
May as well let this thing die. It doesn’t seem like it’s going to be supported that much anymore. Use the vue cli and plugins and you can easily accomplish all the stuff this template does, and it works.

**Comment by modenero** [comment]
as others have pointed out, @ChrisKader's solution works perfectly 👍

in `src/index.ejs`, you need to change`<% if (!process.browser) { %>` to `<% if (!require('process').browser) { %>` and you're in business!

**Comment by PachVerb** [comment]
> @AIMentalModel您是否首先尝试过@LionelGarcia的解决方案-关于从index.ejs文件中删除该部分？我只提到它，因为它对我来说效果很好。
> 
> 链接到评论-> [＃871（评论）](https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-489556092)



> Solved by removing:
> 
> ```
> <% if (!process.browser) { %>
>     <script>
>         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> ```
> 
> from `src/index.ejs:16`
> 
> Might not be the right solution but works as a temporary fix for me. Not sure issue should be closed though!

solved my problem suscces! but ，What causes this problem？

**Comment by PachVerb** [comment]
> Experiencing the same issue on Node 12.2.0. Not sure what causes it, and not entirely convinced the issue is in this repo. Probably a dependency. Removing parts from the template will work for `npm run dev`, but not so much for `npm run build` or `npm run pack`.
> 
> My temporary solution was to do modify `HtmlWebpackPlugin` in `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js`:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```

new questions is module.js:543 Uncaught Error: Cannot find module 'axios' , what happen

**Comment by PachVerb** [comment]
> [nodejs/node#26882](https://github.com/nodejs/node/pull/26882)
> 
> Pretty much in node v12+ you need to explicitly import the process module.
> 
> Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <title>vest</title>
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>       
>       <script>
>         require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>       </script>
>     <% } %>
>   </head>
>   <body>
>     <div id="app"></div>
>     
>     <%  if (!require('process').browser) { %>
>       <script>
>         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>       </script>
>     <% } %>
> 
>     
>   </body>
> </html>
> ```

very good :)

**Comment by osjn** [comment]
> 
> 
> > [nodejs/node#26882](https://github.com/nodejs/node/pull/26882)
> > Pretty much in node v12+ you need to explicitly import the process module.
> > Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.
> > ```
> > <!DOCTYPE html>
> > <html>
> >   <head>
> >     <meta charset="utf-8">
> >     <title>vest</title>
> >     <% if (htmlWebpackPlugin.options.nodeModules) { %>
> >       
> >       <script>
> >         require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
> >       </script>
> >     <% } %>
> >   </head>
> >   <body>
> >     <div id="app"></div>
> >     
> >     <%  if (!require('process').browser) { %>
> >       <script>
> >         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
> >       </script>
> >     <% } %>
> > 
> >     
> >   </body>
> > </html>
> > ```
> 
> very good :)

This is the pefect solution.

**Comment by yanlee26** [comment]
Uncaught Error: Cannot find module 'axios'

**Comment by kingangelAOA** [comment]
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```
Uncaught Error: Cannot find module 'axios'

**Comment by wentianl20** [comment]
> 
> 
> @ChrisKader 你的时非常正确的解决方案，希望大家采用他的解决方案。——node12.8的工作者的一句忠告。——i am from china

独秀同志，赶快落座，你是对的

**Comment by misterpancn** [comment]
> Experiencing the same issue on Node 12.2.0. Not sure what causes it, and not entirely convinced the issue is in this repo. Probably a dependency. Removing parts from the template will work for `npm run dev`, but not so much for `npm run build` or `npm run pack`.
> 
> My temporary solution was to do modify `HtmlWebpackPlugin` in `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js`:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```

The node version was upgraded from 10.16 to 14.0. This error occurred when executing 'NPM run dev'. We solved it this way. Perfect.

**Comment by toudidel** [comment]
Modyfying `HtmlWebpackPlugin` `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js` does not work for me.

system: Linux Mint 19.3
nodejs: v14.7.0
npm: v6.14.7
webpack: v4.44.1

**Comment by kingnand** [comment]
> I edit webpack.renderer.config.js as below:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: process.env.NODE_ENV !== 'production'
>         ? path.resolve(__dirname, '../node_modules')
>         : false
>     }),
> ```
> 
> and then change index.ejs like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="zh">
> <head>
>     <meta charset="utf-8">
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>         
>         <script>
>           require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>         </script>
>     <% } %>
> </head>
> <body>
> 
> <div id="app">
> </div>
> 
> 
> <% if (!htmlWebpackPlugin.options.isBrowser && !htmlWebpackPlugin.options.isDevelopment) { %>
>     <script>
>       window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>     </script>
> <% } %>
> 
> 
> </body>
> </html>
> ```
> 
> it just drops "process" and works perfectly for me.
> 
> I hope this can help you.

it works for me

**Comment by samchenws** [comment]
> > > add this code solved the problem for me
> > > ```js
> > > templateParameters(compilation, assets, options) {
> > >         return {
> > >           compilation: compilation,
> > >           webpack: compilation.getStats().toJson(),
> > >           webpackConfig: compilation.options,
> > >           htmlWebpackPlugin: {
> > >             files: assets,
> > >             options: options
> > >           },
> > >           process,
> > >         };
> > >       }
> > > ```
> > 
> > 
> > where add this your code ?
> 
> ...electron-vue\webpack.renderer.config.js
> ...electron-vue\webpack.web.config.js
> 
> ```
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```

Good,Thanks.

**Comment by pacific202** [comment]
I still can't get this to work after a clean install.  This issue was opened over a year ago.

I guess writing quality code can be difficult sometimes ¯\_(ツ)_/¯

**Comment by jeepxiaozi** [comment]
got the same error, and solved it according to @wubzz 's solution, thank you!

**Comment by willvitorino** [comment]
> Experiencing the same issue on Node 12.2.0. Not sure what causes it, and not entirely convinced the issue is in this repo. Probably a dependency. Removing parts from the template will work for `npm run dev`, but not so much for `npm run build` or `npm run pack`.
> 
> My temporary solution was to do modify `HtmlWebpackPlugin` in `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js`:
> 
> ```js
> new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.resolve(__dirname, '../src/index.ejs'),
>       templateParameters(compilation, assets, options) {
>         return {
>           compilation: compilation,
>           webpack: compilation.getStats().toJson(),
>           webpackConfig: compilation.options,
>           htmlWebpackPlugin: {
>             files: assets,
>             options: options
>           },
>           process,
>         };
>       },
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true
>       },
>       nodeModules: false
>     }),
> ```

Work's for me on Node v14.14.0
 Thanks Guys

**Comment by Aryesh-M** [comment]
I think you should follow this article cum tutorial, it might be helpful!
https://auth0.com/blog/electron-tutorial-building-modern-desktop-apps-with-vue-js/

**Comment by Aimee616** [comment]
> ```
> !require('process').browser
> ```

This works，thanks！

**Comment by sg552** [comment]
Oh my god, still got this error after a fresh installation.  Node version: 14.15.4   
solved by @wubzz 's solution.

**Comment by mklnz** [comment]
Same here, still having the issue on Node v14.15.1 - will try @wubzz 's solution....

**Comment by MertvyeDushi** [comment]
> [nodejs/node#26882](https://github.com/nodejs/node/pull/26882)
> 
> Pretty much in node v12+ you need to explicitly import the process module.
> 
> Only change you need to make is below is update process to require('process'). I Can submit a PR if needed. No changes to your webpack config or anything is needed.
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <title>vest</title>
>     <% if (htmlWebpackPlugin.options.nodeModules) { %>
>       
>       <script>
>         require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
>       </script>
>     <% } %>
>   </head>
>   <body>
>     <div id="app"></div>
>     
>     <%  if (!require('process').browser) { %>
>       <script>
>         if (process.env.NODE_ENV !== 'development') window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
>       </script>
>     <% } %>
> 
>     
>   </body>
> </html>
> ```

It's works for me! Node v. 14.15.0
